// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vcrgcnavuzisolnhnrdo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZjcmdjbmF2dXppc29sbmhucmRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODIxNDc3MDUsImV4cCI6MjA5NzcyMzcwNX0.XYWgUT98zff6jHsdoWfU4LjbcpcTzd6uaHNpbJ8whr8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});